': This program was generated by
': InForm - GUI system for QB64 - Beta version 6
': Fellippe Heitor, 2016/2018 - fellippe@qb64.org - @fellippeheitor
'-----------------------------------------------------------

'Icon: http://www.iconarchive.com/show/keyboard-keys-icons-by-chromatix/hash-icon.html
'Artist: Chromatix
'Iconset: Keyboard Keys Icons (102 icons)
'License: CC Attribution-Noncommercial-No Derivate 4.0
'Commercial usage: Not allowed

$VERSIONINFO:FILEVERSION#=0,0,0,1
$VERSIONINFO:PRODUCTVERSION#=0,0,0,1
$VERSIONINFO:CompanyName=Fellippe Heitor
$VERSIONINFO:FileDescription=Controle De Oficios TJMG
$VERSIONINFO:FileVersion=0.1b
$VERSIONINFO:InternalName=ControlDeOficios.bas
$VERSIONINFO:LegalCopyright=Open source
$VERSIONINFO:OriginalFilename=ControlDeOficios.exe
$VERSIONINFO:ProductName=Controle De Oficios TJMG
$VERSIONINFO:ProductVersion=0.1b
$VERSIONINFO:Comments=Made with QB64.

': Controls' IDs: ------------------------------------------------------------------
DIM SHARED ControleDeOficios AS LONG
DIM SHARED Frame1 AS LONG
DIM SHARED PrximoNmero AS LONG
DIM SHARED ltimoUtilizadoLB AS LONG
DIM SHARED UltimoOficioLB AS LONG
DIM SHARED Label2 AS LONG
DIM SHARED UltimaDescricaoLB AS LONG
DIM SHARED Label3 AS LONG
DIM SHARED UltimoUsuarioLB AS LONG
DIM SHARED Label4 AS LONG
DIM SHARED UsuarioAtualLB AS LONG
DIM SHARED DecriaoOpcionalLB AS LONG
DIM SHARED DescricaoTB AS LONG
DIM SHARED BT AS LONG
DIM SHARED VerHistoricoBT AS LONG
DIM SHARED FirstBT AS LONG, PreviousBT AS LONG
DIM SHARED NextBT AS LONG, LastBT AS LONG

DIM SHARED Ultimo AS LONG, Proximo AS LONG
DIM SHARED Primeiro AS LONG, Atual AS LONG
DIM SHARED Usuario AS STRING
DIM SHARED LastCheck AS SINGLE

IF LEN(COMMAND$) THEN Usuario = COMMAND$

': External modules: ---------------------------------------------------------------
'$INCLUDE:'InForm\InForm.ui'
'$INCLUDE:'InForm\xp.uitheme'
'$INCLUDE:'ControleDeOficios.frm'

': Event procedures: ---------------------------------------------------------------
SUB __UI_BeforeInit

END SUB

SUB __UI_OnLoad
    IniSetForceReload True
    a$ = ReadSetting("oficios.ini", "controle", "UltimoNumero")
    IF LEN(a$) > 0 THEN
        Ultimo = VAL(a$)
        Atual = Ultimo
        Caption(UltimoOficioLB) = a$
        Proximo = Ultimo + 1
        Caption(BT) = LTRIM$(STR$(Proximo))
        Caption(UltimaDescricaoLB) = ReadSetting("", a$, "Descricao")
        Caption(UltimoUsuarioLB) = ReadSetting("", a$, "Usuario")
        Primeiro = VAL(ReadSetting("", "controle", "PrimeiroNumero"))
    ELSE
        Caption(UltimoOficioLB) = "-"
        Caption(UltimaDescricaoLB) = "-"
        Caption(UltimoUsuarioLB) = "-"
        Caption(BT) = "1"
        Proximo = 1
    END IF

    IF LEN(Usuario) = 0 THEN Usuario = "Secretaria Criminal"
    Caption(UsuarioAtualLB) = Usuario
    ToolTip(UltimaDescricaoLB) = "Clique para copiar"
    __UI_Focus = DescricaoTB
    LastCheck = TIMER
    Control(NextBT).Disabled = True
    Control(LastBT).Disabled = True
    DoLocalBackup
END SUB

SUB DoLocalBackup
    ff = FREEFILE
    OPEN "oficios.ini" FOR BINARY AS #ff
    a$ = SPACE$(LOF(ff))
    GET #ff, 1, a$
    CLOSE #ff

    OPEN ENVIRON$("USERPROFILE") + "\oficiosBackup.ini" FOR OUTPUT AS #ff: CLOSE #ff
    OPEN ENVIRON$("USERPROFILE") + "\oficiosBackup.ini" FOR BINARY AS #ff
    PUT #ff, 1, a$
    CLOSE #ff
END SUB

SUB __UI_BeforeUpdateDisplay
    IF TIMER - LastCheck > 1 THEN
        Refresh
    END IF
END SUB

SUB Refresh
    a$ = ReadSetting("", "controle", "UltimoNumero")
    IF VAL(a$) <> Ultimo THEN
        Ultimo = VAL(a$)
        Caption(UltimoOficioLB) = a$
        Proximo = Ultimo + 1
        Caption(BT) = LTRIM$(STR$(Proximo))
        Caption(UltimaDescricaoLB) = ReadSetting("", a$, "Descricao")
        Caption(UltimoUsuarioLB) = ReadSetting("", a$, "Usuario")
    END IF
    LastCheck = TIMER
END SUB

SUB __UI_BeforeUnload

END SUB

SUB __UI_Click (id AS LONG)
    Control(FirstBT).Disabled = False
    Control(PreviousBT).Disabled = False
    Control(NextBT).Disabled = False
    Control(LastBT).Disabled = False
    SELECT EVERYCASE id
        CASE BT
            Answer = MessageBox("Confirma?", "", MsgBox_YesNo + MsgBox_Question)
            IF Answer = MsgBox_Yes THEN
                a$ = LTRIM$(STR$(Proximo))
                _CLIPBOARD$ = a$
                WriteSetting "", a$, "Usuario", Usuario
                IF LEN(Text(DescricaoTB)) THEN WriteSetting "", a$, "Descricao", Text(DescricaoTB)
                WriteSetting "", "controle", "UltimoNumero", a$

                Ultimo = Proximo
                Atual = Ultimo
                Control(NextBT).Disabled = True
                Control(LastBT).Disabled = True
                Proximo = VAL(a$) + 1
                Caption(BT) = LTRIM$(STR$(Proximo))
                Caption(UltimoOficioLB) = a$
                Proximo = VAL(a$) + 1
                Caption(BT) = LTRIM$(STR$(Proximo))
                Caption(UltimaDescricaoLB) = Text(DescricaoTB)
                Caption(UltimoUsuarioLB) = Usuario
                Text(DescricaoTB) = ""
                __UI_Focus = DescricaoTB
                DoLocalBackup
            END IF
        CASE VerHistoricoBT
            SHELL _HIDE _DONTWAIT "start oficios.ini"
        CASE UltimaDescricaoLB
            IF LEN(Caption(UltimaDescricaoLB)) THEN
                Text(DescricaoTB) = Caption(UltimaDescricaoLB)
                Control(DescricaoTB).Cursor = LEN(Text(DescricaoTB))
                __UI_Focus = DescricaoTB
            END IF
        CASE FirstBT
            Atual = Primeiro
        CASE PreviousBT
            Atual = Atual + (Atual - 1 >= Primeiro)
        CASE NextBT
            Atual = Atual - (Atual + 1 <= Ultimo)
        CASE LastBT
            Atual = Ultimo
        CASE FirstBT, PreviousBT, NextBT, LastBT
            Caption(UltimoOficioLB) = LTRIM$(STR$(Atual))
            Caption(UltimaDescricaoLB) = ReadSetting("", STR$(Atual), "Descricao")
            Caption(UltimoUsuarioLB) = ReadSetting("", STR$(Atual), "Usuario")
    END SELECT
    IF Atual = Ultimo THEN
        Control(NextBT).Disabled = True
        Control(LastBT).Disabled = True
    END IF
    IF Atual = Primeiro THEN
        Control(FirstBT).Disabled = True
        Control(PreviousBT).Disabled = True
    END IF
END SUB

SUB __UI_MouseEnter (id AS LONG)
    SELECT CASE id
        CASE ControleDeOficios

        CASE Frame1

        CASE PrximoNmero

        CASE ltimoUtilizadoLB

        CASE UltimoOficioLB

        CASE Label2

        CASE UltimaDescricaoLB

        CASE Label3

        CASE UltimoUsuarioLB

        CASE Label4

        CASE UsuarioAtualLB

        CASE DecriaoOpcionalLB

        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_MouseLeave (id AS LONG)
    SELECT CASE id
        CASE ControleDeOficios

        CASE Frame1

        CASE PrximoNmero

        CASE ltimoUtilizadoLB

        CASE UltimoOficioLB

        CASE Label2

        CASE UltimaDescricaoLB

        CASE Label3

        CASE UltimoUsuarioLB

        CASE Label4

        CASE UsuarioAtualLB

        CASE DecriaoOpcionalLB

        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_FocusIn (id AS LONG)
    SELECT CASE id
        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_FocusOut (id AS LONG)
    SELECT CASE id
        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_MouseDown (id AS LONG)
    SELECT CASE id
        CASE ControleDeOficios

        CASE Frame1

        CASE PrximoNmero

        CASE ltimoUtilizadoLB

        CASE UltimoOficioLB

        CASE Label2

        CASE UltimaDescricaoLB

        CASE Label3

        CASE UltimoUsuarioLB

        CASE Label4

        CASE UsuarioAtualLB

        CASE DecriaoOpcionalLB

        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_MouseUp (id AS LONG)
    SELECT CASE id
        CASE ControleDeOficios

        CASE Frame1

        CASE PrximoNmero

        CASE ltimoUtilizadoLB

        CASE UltimoOficioLB

        CASE Label2

        CASE UltimaDescricaoLB

        CASE Label3

        CASE UltimoUsuarioLB

        CASE Label4

        CASE UsuarioAtualLB

        CASE DecriaoOpcionalLB

        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_KeyPress (id AS LONG)
    SELECT CASE id
        CASE DescricaoTB

        CASE BT

    END SELECT
END SUB

SUB __UI_TextChanged (id AS LONG)
    SELECT CASE id
        CASE DescricaoTB

    END SELECT
END SUB

SUB __UI_ValueChanged (id AS LONG)
    SELECT CASE id
    END SELECT
END SUB

SUB __UI_FormResized

END SUB

'$include:'ini.bm'
